use_frameworks!

platform :ios, '9.0'

target 'UIFontIconsDemo' do
 pod 'UIFontIcons/MaterialIcons', path: '../../'
 pod 'UIFontIcons/Feather', path: '../../'
 pod 'UIFontIcons/FontAwesome', path: '../../'
 pod 'UIFontLoader', :git => 'https://github.com/Appsaurus/UIFontLoader'

end

